import client from "./pgClient.js";


app.post('/formSurveyMock', async (req, res) => {
    const surveyMock = [
        {
            "StudentId": "U59540600",
            "Organization": "Meejo",
            "Responsibilities": "Limited technical experience with coding except classes, more experience with PM.",
            "Country": "USA",
            "State": "MA",
            "TimezoneFromUTC": -5,
            "Coding": 10,
            "Requirements": 30,
            "Testing": 10,
            "UIDesign": 30,
            "ProjectManager": 80,
            "SurveyDate": "2023-02-01"
        },
        {
            "StudentId": "U64438875"  ,
            "Organization": "Oyope",
            "Responsibilities": "More experience with coding, but have had classes in other areas.",
            "Country": "USA",
            "State": "MA",
            "TimezoneFromUTC": -5,
            "Coding": 60,
            "Requirements": 40,
            "Testing": 20,
            "UIDesign": 20,
            "ProjectManager": 20,
            "SurveyDate": "2023-02-01"
        },
        {
            "StudentId": "U65443909"  ,
            "Organization": "Skipstorm",
            "Responsibilities": "Just starting in the program, but I have side coding projects.",
            "Country": "USA",
            "State": "MA",
            "TimezoneFromUTC": -5,
            "Coding": 20,
            "Requirements": 20,
            "Testing": 20,
            "UIDesign": 20,
            "ProjectManager": 20,
            "SurveyDate": "2023-02-01"
        },
        {
            "StudentId": "U13466334"  ,
            "Organization": "Linktype",
            "Responsibilities": "I am a project specialist at work.",
            "Country": "USA",
            "State": "MA",
            "TimezoneFromUTC": -5,
            "Coding": 20,
            "Requirements": 20,
            "Testing": 20,
            "UIDesign": 20,
            "ProjectManager": 60,
            "SurveyDate": "2023-02-01"
        },
        {
            "StudentId": "U87570131"  ,
            "Organization": "Eidel",
            "Responsibilities": "More experience with coding.",
            "Country": "USA",
            "State": "MA",
            "TimezoneFromUTC": -5,
            "Coding": 70,
            "Requirements": 50,
            "Testing": 40,
            "UIDesign": 40,
            "ProjectManager": 20,
            "SurveyDate": "2023-02-02"
        },
        {
            "StudentId": "U58239581"  ,
            "Organization": "Gigaclub",
            "Responsibilities": "I only have experience through the program, but I have a concentration in IT Project Management.",
            "Country": "USA",
            "State": "MA",
            "TimezoneFromUTC": -5,
            "Coding": 30,
            "Requirements":30,
            "Testing": 20,
            "UIDesign": 30,
            "ProjectManager": 60,
            "SurveyDate": "2023-02-02"
        },
        {
            "StudentId": "U77347864"  ,
            "Organization": "Rhynoodle",
            "Responsibilities": "I have some experience managing user requirements at work, but more direct experience with coding.",
            "Country": "USA",
            "State": "MA",
            "TimezoneFromUTC": -5,
            "Coding": 50,
            "Requirements":40,
            "Testing": 20,
            "UIDesign": 20,
            "ProjectManager": 10,
            "SurveyDate": "2023-02-02"
        },
        {
            "StudentId": "U37800149"  ,
            "Organization": "Devpulse",
            "Responsibilities": "Just classes.",
            "Country": "USA",
            "State": "IL",
            "TimezoneFromUTC": -6,
            "Coding": 10,
            "Requirements":10,
            "Testing": 10,
            "UIDesign": 10,
            "ProjectManager": 10,
            "SurveyDate": "2023-02-02"
        },
        {
            "StudentId": "U82312547"  ,
            "Organization": "Skipfire",
            "Responsibilities": "JI've had some exposure in all areas.",
            "Country": "USA",
            "State": "MA",
            "TimezoneFromUTC": -5,
            "Coding": 20,
            "Requirements":20,
            "Testing": 10,
            "UIDesign": 30,
            "ProjectManager": 40,
            "SurveyDate": "2023-02-03"
        },
        {
            "StudentId": "U73686009"  ,
            "Organization": "Jabberstorm",
            "Responsibilities": "I manage coding and requirements on a daily basis at work.",
            "Country": "USA",
            "State": "MA",
            "TimezoneFromUTC": -5,
            "Coding": 90,
            "Requirements":40,
            "Testing": 80,
            "UIDesign": 20,
            "ProjectManager": 10,
            "SurveyDate": "2023-02-03"
        },
        {
            "StudentId": "U25140621"  ,
            "Organization": "Edgeblab",
            "Responsibilities": "On development team.",
            "Country": "Other",
            "State": "Other",
            "TimezoneFromUTC": -99,
            "Coding": 70,
            "Requirements":70,
            "Testing": 70,
            "UIDesign": 20,
            "ProjectManager": 20,
            "SurveyDate": "2023-02-03"
        },
        {
            "StudentId": "U84860814"  ,
            "Organization": "Kare",
            "Responsibilities": "I provide customer support at a tech company.",
            "Country": "USA",
            "State": "MA",
            "TimezoneFromUTC": -5,
            "Coding": 10,
            "Requirements": 10,
            "Testing": 10,
            "UIDesign": 10,
            "ProjectManager": 10,
            "SurveyDate": "2023-02-04"
        },
        {
            "StudentId": "U24672585"  ,
            "Organization": "Eire",
            "Responsibilities": "I have some coding and product owner experience.",
            "Country": "USA",
            "State": "MA",
            "TimezoneFromUTC": -5,
            "Coding": 60,
            "Requirements": 60,
            "Testing": 60,
            "UIDesign": 10,
            "ProjectManager": 10,
            "SurveyDate": "2023-02-04"
        },
        {
            "StudentId": "U32989195"  ,
            "Organization": "Rhyloo",
            "Responsibilities": "I work in all areas, but I've focused my BU degree as PM.",
            "Country": "USA",
            "State": "TX",
            "TimezoneFromUTC": -6,
            "Coding": 50,
            "Requirements": 50,
            "Testing": 50,
            "UIDesign": 50,
            "ProjectManager": 60,
            "SurveyDate": "2023-02-04"
        },
        {
            "StudentId": "U31976781"  ,
            "Organization": "Skinder",
            "Responsibilities": "Front end experience",
            "Country": "USA",
            "State": "IL",
            "TimezoneFromUTC": -6,
            "Coding": 60,
            "Requirements": 50,
            "Testing": 60,
            "UIDesign": 60,
            "ProjectManager": 10,
            "SurveyDate": "2023-02-04"
        },
        {
            "StudentId": "U33498445",
            "Organization": "Vinder",
            "Responsibilities": "I have taken some UX/UI courses outside of BU.  This is the area most interested in.",
            "Country": "USA",
            "State": "CO",
            "TimezoneFromUTC": -7,
            "Coding": 10,
            "Requirements": 10,
            "Testing": 10,
            "UIDesign": 50,
            "ProjectManager": 10,
            "SurveyDate": "2023-02-04"
        },
        {
            "StudentId": "U34565776",
            "Organization": "Zooveo",
            "Responsibilities": "Coding experience but would like to learn more/better ways to test.",
            "Country": "USA",
            "State": "CO",
            "TimezoneFromUTC": -7,
            "Coding": 70,
            "Requirements": 50,
            "Testing": 80,
            "UIDesign": 10,
            "ProjectManager": 10,
            "SurveyDate": "2023-02-04"
        },
        {
            "StudentId": "U70270028",
            "Organization": "Blogtags",
            "Responsibilities": "Working on soft dev degree, but minimal professional experience.",
            "Country": "USA",
            "State": "MA",
            "TimezoneFromUTC": -5,
            "Coding": 50,
            "Requirements": 50,
            "Testing": 50,
            "UIDesign": 20,
            "ProjectManager": 20,
            "SurveyDate": "2023-02-05"
        },
        {
            "StudentId": "U83007537",
            "Organization": "Flipstorm",
            "Responsibilities": "Intern last summer providing support for testing.",
            "Country": "USA",
            "State": "MA",
            "TimezoneFromUTC": -5,
            "Coding": 40,
            "Requirements": 30,
            "Testing": 60,
            "UIDesign": 10,
            "ProjectManager": 10,
            "SurveyDate": "2023-02-05"
        },
        {
            "StudentId": "U99385487",
            "Organization": "Wikido",
            "Responsibilities": "Customer success at work, with some project experience.",
            "Country": "USA",
            "State": "CA",
            "TimezoneFromUTC": -8,
            "Coding": 20,
            "Requirements": 20,
            "Testing": 20,
            "UIDesign": 20,
            "ProjectManager": 70,
            "SurveyDate": "2023-02-05"
        },
        {
            "StudentId": "U51749303",
            "Organization": "Photojam",
            "Responsibilities": "I am a programmer at work and just now exploring my major.",
            "Country": "USA",
            "State": "CA",
            "TimezoneFromUTC": -8,
            "Coding": 90,
            "Requirements": 10,
            "Testing": 10,
            "UIDesign": 10,
            "ProjectManager": 10,
            "SurveyDate": "2023-02-05"
        },
        {
            "StudentId": "U25761203",
            "Organization": "Buzzster",
            "Responsibilities": "More experience with healthcare info databases.",
            "Country": "USA",
            "State": "IL",
            "TimezoneFromUTC": -6,
            "Coding": 10,
            "Requirements": 20,
            "Testing": 10,
            "UIDesign": 40,
            "ProjectManager": 30,
            "SurveyDate": "2023-02-05"
        },
        {
            "StudentId": "U99979695",
            "Organization": "Twitterbridge",
            "Responsibilities": "Experience coding as well as experience with testing and user requirements.",
            "Country": "USA",
            "State": "TX",
            "TimezoneFromUTC": -6,
            "Coding": 30,
            "Requirements": 60,
            "Testing": 10,
            "UIDesign": 50,
            "ProjectManager": 30,
            "SurveyDate": "2023-02-05"
        },
        {
            "StudentId": "U65376465",
            "Organization": "Riffpedia",
            "Responsibilities": "More experience in UX.",
            "Country": "USA",
            "State": "TX",
            "TimezoneFromUTC": -6,
            "Coding": 20,
            "Requirements": 20,
            "Testing": 20,
            "UIDesign": 60,
            "ProjectManager": 20,
            "SurveyDate": "2023-02-05"
        },
        {
            "StudentId": "U15250896",
            "Organization": "Mita",
            "Responsibilities": "More experience on the coding, requirements, test side, but would like to learn more about UI.",
            "Country": "USA",
            "State": "CO",
            "TimezoneFromUTC": -7,
            "Coding": 60,
            "Requirements": 60,
            "Testing": 60,
            "UIDesign": 50,
            "ProjectManager": 20,
            "SurveyDate": "2023-02-05"
        },
        {
            "StudentId": "U49924857",
            "Organization": "Vimbo",
            "Responsibilities": "More technical - prefer not to manage team/project.",
            "Country": "USA",
            "State": "CO",
            "TimezoneFromUTC": -7,
            "Coding": 70,
            "Requirements": 50,
            "Testing": 70,
            "UIDesign": 20,
            "ProjectManager": 20,
            "SurveyDate": "2023-02-05"
        },
        {
            "StudentId": "U14810016",
            "Organization": "Omba",
            "Responsibilities": "I do not currently have a major, but I work on a development team.",
            "Country": "USA",
            "State": "CA",
            "TimezoneFromUTC": -8,
            "Coding": 10,
            "Requirements": 10,
            "Testing": 10,
            "UIDesign": 10,
            "ProjectManager": 20,
            "SurveyDate": "2023-02-06"
        },
        {
            "StudentId": "U10332425",
            "Organization": "Bluezoom",
            "Responsibilities": "I currently work for a non-profit, so limited technical experience.",
            "Country": "USA",
            "State": "CA",
            "TimezoneFromUTC": -8,
            "Coding": 30,
            "Requirements": 30,
            "Testing": 30,
            "UIDesign": 30,
            "ProjectManager": 60,
            "SurveyDate": "2023-02-06"
        },
        {
            "StudentId": "U87207965",
            "Organization": "Devify",
            "Responsibilities": "I work more with data analytics, but could with some of the documention in UI.",
            "Country": "USA",
            "State": "CA",
            "TimezoneFromUTC": -8,
            "Coding": 40,
            "Requirements": 50,
            "Testing": 10,
            "UIDesign": 60,
            "ProjectManager": 60,
            "SurveyDate": "2023-02-06"
        },
        {
            "StudentId": "U11004078",
            "Organization": "Demizz",
            "Responsibilities": "I work on wireframes at work.",
            "Country": "USA",
            "State": "CA",
            "TimezoneFromUTC": -8,
            "Coding": 60,
            "Requirements": 40,
            "Testing": 60,
            "UIDesign": 60,
            "ProjectManager": 10,
            "SurveyDate": "2023-02-06"
        },
        {
            "StudentId": "U28076747",
            "Organization": "Einti",
            "Responsibilities": "I work in UX and would be comfortable assisting with UI.",
            "Country": "USA",
            "State": "CA",
            "TimezoneFromUTC": -8,
            "Coding": 40,
            "Requirements": 40,
            "Testing": 40,
            "UIDesign": 70,
            "ProjectManager": 30,
            "SurveyDate": "2023-02-06"
        },
        {
            "StudentId": "U16412496",
            "Organization": "Photobean",
            "Responsibilities": "I've touch on all areas at work - probably more experience coding/testing.",
            "Country": "USA",
            "State": "IL",
            "TimezoneFromUTC": -6,
            "Coding": 60,
            "Requirements": 60,
            "Testing": 60,
            "UIDesign": 40,
            "ProjectManager": 20,
            "SurveyDate": "2023-02-06"
        },
        {
            "StudentId": "U12613250",
            "Organization": "Jabbersphere",
            "Responsibilities": "Some work experience in each area.  Work on grad certificate it data.",
            "Country": "USA",
            "State": "CO",
            "TimezoneFromUTC": -7,
            "Coding": 40,
            "Requirements": 40,
            "Testing": 40,
            "UIDesign": 40,
            "ProjectManager": 40,
            "SurveyDate": "2023-02-06"
        }
    ]

    try {
        surveyMock.map(async (survey) => {
            const data = survey; //JSON of object to insert
            await client.query(
                "INSERT INTO SURVEYS (StudentId, Organization, Responsibilities, Country, State, TimezoneFromUTC, Coding, Requirements, Testing, UIDesign, ProjectManager, Experience, SurveyDate) " +
                "VALUES($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13);",[data.StudentId, data.Organization, data.Responsibilities, data.Country, data.State, data.TimezoneFromUTC, data.Coding, data.Requirements, data.Testing, data.UIDesign, data.ProjectManager, data.Experience, new Date().toLocaleDateString()]
            );
        })}
    catch (err) {
        console.log('ERROR')
        res.status(500).send("Server error")
    }
    finally {
        console.log('SEND')
        res.status(200).send("Roster complete")
    }
});


app.post('/formSurveyMock', async (req, res) => {
    const surveyMock = [
        {
            "StudentId": "U59540600",
            "Organization": "Meejo",
            "Responsibilities": "Limited technical experience with coding except classes, more experience with PM.",
            "Country": "USA",
            "State": "MA",
            "TimezoneFromUTC": -5,
            "Coding": 10,
            "Requirements": 30,
            "Testing": 10,
            "UIDesign": 30,
            "ProjectManager": 80,
            "SurveyDate": "2023-02-01"
        },
        {
            "StudentId": "U64438875"  ,
            "Organization": "Oyope",
            "Responsibilities": "More experience with coding, but have had classes in other areas.",
            "Country": "USA",
            "State": "MA",
            "TimezoneFromUTC": -5,
            "Coding": 60,
            "Requirements": 40,
            "Testing": 20,
            "UIDesign": 20,
            "ProjectManager": 20,
            "SurveyDate": "2023-02-01"
        },
        {
            "StudentId": "U65443909"  ,
            "Organization": "Skipstorm",
            "Responsibilities": "Just starting in the program, but I have side coding projects.",
            "Country": "USA",
            "State": "MA",
            "TimezoneFromUTC": -5,
            "Coding": 20,
            "Requirements": 20,
            "Testing": 20,
            "UIDesign": 20,
            "ProjectManager": 20,
            "SurveyDate": "2023-02-01"
        },
        {
            "StudentId": "U13466334"  ,
            "Organization": "Linktype",
            "Responsibilities": "I am a project specialist at work.",
            "Country": "USA",
            "State": "MA",
            "TimezoneFromUTC": -5,
            "Coding": 20,
            "Requirements": 20,
            "Testing": 20,
            "UIDesign": 20,
            "ProjectManager": 60,
            "SurveyDate": "2023-02-01"
        },
        {
            "StudentId": "U87570131"  ,
            "Organization": "Eidel",
            "Responsibilities": "More experience with coding.",
            "Country": "USA",
            "State": "MA",
            "TimezoneFromUTC": -5,
            "Coding": 70,
            "Requirements": 50,
            "Testing": 40,
            "UIDesign": 40,
            "ProjectManager": 20,
            "SurveyDate": "2023-02-02"
        },
        {
            "StudentId": "U58239581"  ,
            "Organization": "Gigaclub",
            "Responsibilities": "I only have experience through the program, but I have a concentration in IT Project Management.",
            "Country": "USA",
            "State": "MA",
            "TimezoneFromUTC": -5,
            "Coding": 30,
            "Requirements":30,
            "Testing": 20,
            "UIDesign": 30,
            "ProjectManager": 60,
            "SurveyDate": "2023-02-02"
        },
        {
            "StudentId": "U77347864"  ,
            "Organization": "Rhynoodle",
            "Responsibilities": "I have some experience managing user requirements at work, but more direct experience with coding.",
            "Country": "USA",
            "State": "MA",
            "TimezoneFromUTC": -5,
            "Coding": 50,
            "Requirements":40,
            "Testing": 20,
            "UIDesign": 20,
            "ProjectManager": 10,
            "SurveyDate": "2023-02-02"
        },
        {
            "StudentId": "U37800149"  ,
            "Organization": "Devpulse",
            "Responsibilities": "Just classes.",
            "Country": "USA",
            "State": "IL",
            "TimezoneFromUTC": -6,
            "Coding": 10,
            "Requirements":10,
            "Testing": 10,
            "UIDesign": 10,
            "ProjectManager": 10,
            "SurveyDate": "2023-02-02"
        },
        {
            "StudentId": "U82312547"  ,
            "Organization": "Skipfire",
            "Responsibilities": "JI've had some exposure in all areas.",
            "Country": "USA",
            "State": "MA",
            "TimezoneFromUTC": -5,
            "Coding": 20,
            "Requirements":20,
            "Testing": 10,
            "UIDesign": 30,
            "ProjectManager": 40,
            "SurveyDate": "2023-02-03"
        },
        {
            "StudentId": "U73686009"  ,
            "Organization": "Jabberstorm",
            "Responsibilities": "I manage coding and requirements on a daily basis at work.",
            "Country": "USA",
            "State": "MA",
            "TimezoneFromUTC": -5,
            "Coding": 90,
            "Requirements":40,
            "Testing": 80,
            "UIDesign": 20,
            "ProjectManager": 10,
            "SurveyDate": "2023-02-03"
        },
        {
            "StudentId": "U25140621"  ,
            "Organization": "Edgeblab",
            "Responsibilities": "On development team.",
            "Country": "Other",
            "State": "Other",
            "TimezoneFromUTC": -99,
            "Coding": 70,
            "Requirements":70,
            "Testing": 70,
            "UIDesign": 20,
            "ProjectManager": 20,
            "SurveyDate": "2023-02-03"
        },
        {
            "StudentId": "U84860814"  ,
            "Organization": "Kare",
            "Responsibilities": "I provide customer support at a tech company.",
            "Country": "USA",
            "State": "MA",
            "TimezoneFromUTC": -5,
            "Coding": 10,
            "Requirements": 10,
            "Testing": 10,
            "UIDesign": 10,
            "ProjectManager": 10,
            "SurveyDate": "2023-02-04"
        },
        {
            "StudentId": "U24672585"  ,
            "Organization": "Eire",
            "Responsibilities": "I have some coding and product owner experience.",
            "Country": "USA",
            "State": "MA",
            "TimezoneFromUTC": -5,
            "Coding": 60,
            "Requirements": 60,
            "Testing": 60,
            "UIDesign": 10,
            "ProjectManager": 10,
            "SurveyDate": "2023-02-04"
        },
        {
            "StudentId": "U32989195"  ,
            "Organization": "Rhyloo",
            "Responsibilities": "I work in all areas, but I've focused my BU degree as PM.",
            "Country": "USA",
            "State": "TX",
            "TimezoneFromUTC": -6,
            "Coding": 50,
            "Requirements": 50,
            "Testing": 50,
            "UIDesign": 50,
            "ProjectManager": 60,
            "SurveyDate": "2023-02-04"
        },
        {
            "StudentId": "U31976781"  ,
            "Organization": "Skinder",
            "Responsibilities": "Front end experience",
            "Country": "USA",
            "State": "IL",
            "TimezoneFromUTC": -6,
            "Coding": 60,
            "Requirements": 50,
            "Testing": 60,
            "UIDesign": 60,
            "ProjectManager": 10,
            "SurveyDate": "2023-02-04"
        },
        {
            "StudentId": "U33498445",
            "Organization": "Vinder",
            "Responsibilities": "I have taken some UX/UI courses outside of BU.  This is the area most interested in.",
            "Country": "USA",
            "State": "CO",
            "TimezoneFromUTC": -7,
            "Coding": 10,
            "Requirements": 10,
            "Testing": 10,
            "UIDesign": 50,
            "ProjectManager": 10,
            "SurveyDate": "2023-02-04"
        },
        {
            "StudentId": "U34565776",
            "Organization": "Zooveo",
            "Responsibilities": "Coding experience but would like to learn more/better ways to test.",
            "Country": "USA",
            "State": "CO",
            "TimezoneFromUTC": -7,
            "Coding": 70,
            "Requirements": 50,
            "Testing": 80,
            "UIDesign": 10,
            "ProjectManager": 10,
            "SurveyDate": "2023-02-04"
        },
        {
            "StudentId": "U70270028",
            "Organization": "Blogtags",
            "Responsibilities": "Working on soft dev degree, but minimal professional experience.",
            "Country": "USA",
            "State": "MA",
            "TimezoneFromUTC": -5,
            "Coding": 50,
            "Requirements": 50,
            "Testing": 50,
            "UIDesign": 20,
            "ProjectManager": 20,
            "SurveyDate": "2023-02-05"
        },
        {
            "StudentId": "U83007537",
            "Organization": "Flipstorm",
            "Responsibilities": "Intern last summer providing support for testing.",
            "Country": "USA",
            "State": "MA",
            "TimezoneFromUTC": -5,
            "Coding": 40,
            "Requirements": 30,
            "Testing": 60,
            "UIDesign": 10,
            "ProjectManager": 10,
            "SurveyDate": "2023-02-05"
        },
        {
            "StudentId": "U99385487",
            "Organization": "Wikido",
            "Responsibilities": "Customer success at work, with some project experience.",
            "Country": "USA",
            "State": "CA",
            "TimezoneFromUTC": -8,
            "Coding": 20,
            "Requirements": 20,
            "Testing": 20,
            "UIDesign": 20,
            "ProjectManager": 70,
            "SurveyDate": "2023-02-05"
        },
        {
            "StudentId": "U51749303",
            "Organization": "Photojam",
            "Responsibilities": "I am a programmer at work and just now exploring my major.",
            "Country": "USA",
            "State": "CA",
            "TimezoneFromUTC": -8,
            "Coding": 90,
            "Requirements": 10,
            "Testing": 10,
            "UIDesign": 10,
            "ProjectManager": 10,
            "SurveyDate": "2023-02-05"
        },
        {
            "StudentId": "U25761203",
            "Organization": "Buzzster",
            "Responsibilities": "More experience with healthcare info databases.",
            "Country": "USA",
            "State": "IL",
            "TimezoneFromUTC": -6,
            "Coding": 10,
            "Requirements": 20,
            "Testing": 10,
            "UIDesign": 40,
            "ProjectManager": 30,
            "SurveyDate": "2023-02-05"
        },
        {
            "StudentId": "U99979695",
            "Organization": "Twitterbridge",
            "Responsibilities": "Experience coding as well as experience with testing and user requirements.",
            "Country": "USA",
            "State": "TX",
            "TimezoneFromUTC": -6,
            "Coding": 30,
            "Requirements": 60,
            "Testing": 10,
            "UIDesign": 50,
            "ProjectManager": 30,
            "SurveyDate": "2023-02-05"
        },
        {
            "StudentId": "U65376465",
            "Organization": "Riffpedia",
            "Responsibilities": "More experience in UX.",
            "Country": "USA",
            "State": "TX",
            "TimezoneFromUTC": -6,
            "Coding": 20,
            "Requirements": 20,
            "Testing": 20,
            "UIDesign": 60,
            "ProjectManager": 20,
            "SurveyDate": "2023-02-05"
        },
        {
            "StudentId": "U15250896",
            "Organization": "Mita",
            "Responsibilities": "More experience on the coding, requirements, test side, but would like to learn more about UI.",
            "Country": "USA",
            "State": "CO",
            "TimezoneFromUTC": -7,
            "Coding": 60,
            "Requirements": 60,
            "Testing": 60,
            "UIDesign": 50,
            "ProjectManager": 20,
            "SurveyDate": "2023-02-05"
        },
        {
            "StudentId": "U49924857",
            "Organization": "Vimbo",
            "Responsibilities": "More technical - prefer not to manage team/project.",
            "Country": "USA",
            "State": "CO",
            "TimezoneFromUTC": -7,
            "Coding": 70,
            "Requirements": 50,
            "Testing": 70,
            "UIDesign": 20,
            "ProjectManager": 20,
            "SurveyDate": "2023-02-05"
        },
        {
            "StudentId": "U14810016",
            "Organization": "Omba",
            "Responsibilities": "I do not currently have a major, but I work on a development team.",
            "Country": "USA",
            "State": "CA",
            "TimezoneFromUTC": -8,
            "Coding": 10,
            "Requirements": 10,
            "Testing": 10,
            "UIDesign": 10,
            "ProjectManager": 20,
            "SurveyDate": "2023-02-06"
        },
        {
            "StudentId": "U10332425",
            "Organization": "Bluezoom",
            "Responsibilities": "I currently work for a non-profit, so limited technical experience.",
            "Country": "USA",
            "State": "CA",
            "TimezoneFromUTC": -8,
            "Coding": 30,
            "Requirements": 30,
            "Testing": 30,
            "UIDesign": 30,
            "ProjectManager": 60,
            "SurveyDate": "2023-02-06"
        },
        {
            "StudentId": "U87207965",
            "Organization": "Devify",
            "Responsibilities": "I work more with data analytics, but could with some of the documention in UI.",
            "Country": "USA",
            "State": "CA",
            "TimezoneFromUTC": -8,
            "Coding": 40,
            "Requirements": 50,
            "Testing": 10,
            "UIDesign": 60,
            "ProjectManager": 60,
            "SurveyDate": "2023-02-06"
        },
        {
            "StudentId": "U11004078",
            "Organization": "Demizz",
            "Responsibilities": "I work on wireframes at work.",
            "Country": "USA",
            "State": "CA",
            "TimezoneFromUTC": -8,
            "Coding": 60,
            "Requirements": 40,
            "Testing": 60,
            "UIDesign": 60,
            "ProjectManager": 10,
            "SurveyDate": "2023-02-06"
        },
        {
            "StudentId": "U28076747",
            "Organization": "Einti",
            "Responsibilities": "I work in UX and would be comfortable assisting with UI.",
            "Country": "USA",
            "State": "CA",
            "TimezoneFromUTC": -8,
            "Coding": 40,
            "Requirements": 40,
            "Testing": 40,
            "UIDesign": 70,
            "ProjectManager": 30,
            "SurveyDate": "2023-02-06"
        },
        {
            "StudentId": "U16412496",
            "Organization": "Photobean",
            "Responsibilities": "I've touch on all areas at work - probably more experience coding/testing.",
            "Country": "USA",
            "State": "IL",
            "TimezoneFromUTC": -6,
            "Coding": 60,
            "Requirements": 60,
            "Testing": 60,
            "UIDesign": 40,
            "ProjectManager": 20,
            "SurveyDate": "2023-02-06"
        },
        {
            "StudentId": "U12613250",
            "Organization": "Jabbersphere",
            "Responsibilities": "Some work experience in each area.  Work on grad certificate it data.",
            "Country": "USA",
            "State": "CO",
            "TimezoneFromUTC": -7,
            "Coding": 40,
            "Requirements": 40,
            "Testing": 40,
            "UIDesign": 40,
            "ProjectManager": 40,
            "SurveyDate": "2023-02-06"
        }
    ]
    try {
        surveyMock.map(async (survey) => {
            const data = survey; //JSON of object to insert
            await client.query(
                "INSERT INTO SURVEYS (StudentId, Organization, Responsibilities, Country, State, TimezoneFromUTC, Coding, Requirements, Testing, UIDesign, ProjectManager, SurveyDate) " +
                "VALUES($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12);",[data.StudentId, data.Organization, data.Responsibilities, data.Country, data.State, data.TimezoneFromUTC, data.Coding, data.Requirements, data.Testing, data.UIDesign, data.ProjectManager, data.SurveyDate]
            );
        })}
    catch (err) {
        console.log('ERROR')
        res.status(500).send("Server error")
    }
    finally {
        console.log('SEND')
        res.status(200).send("Roster complete")
    }
});


app.post('/formStudentMock', async (req, res) => {
    const studentMock = [
        {
            "StudentId":"U58239581",
            "StudentDashId":"U58-23-9581",
            "StudentFirst":"Winslow",
            "StudentMiddle":"",
            "StudentLast":"Antalffy",
            "StudentName":"Antalffy,Winslow",
            "Email":"AntalffyW@bu.edu",
            "RegStatus":"REG",
            "ClassYr":"Grad 1st",
            "Col":"MET",
            "Pgm":"42",
            "Concentration1":"Computer Info Systms",
            "Type1":"Major",
            "Concentration2":"IT project Managemnt",
            "Type2":"Subcn",
            "CredHrs":"4",
            "SettledInd":"Y",
            "FullPart":"Full",
            "PhoneNbr":"",
            "RegDt":"11/01/2022"
        },
        {
            "StudentId":"U99385487",
            "StudentDashId":"U99-38-5487",
            "StudentFirst":"Alphonse",
            "StudentMiddle":"",
            "StudentLast":"Bauer",
            "StudentName":"Bauer,Alphonse",
            "Email":"BauerA@bu.edu",
            "RegStatus":"REG",
            "ClassYr":"Grad 3rd",
            "Col":"MET",
            "Pgm":"49",
            "Concentration1":"Computer Info Systms",
            "Type1":"Major",
            "Concentration2":"IT project Managemnt",
            "Type2":"Subcn",
            "CredHrs":"4",
            "SettledInd":"Y",
            "FullPart":"Part",
            "PhoneNbr":"",
            "RegDt":"10/24/2022"
        },
        {
            "StudentId":"U33498445",
            "StudentDashId":"U33-49-8445",
            "StudentFirst":"Mollee",
            "StudentMiddle":"",
            "StudentLast":"Baxstair",
            "StudentName":"Baxstair,Mollee",
            "Email":"BaxstairM@bu.edu",
            "RegStatus":"REG",
            "ClassYr":"Nondeg",
            "Col":"MET",
            "Pgm":"40",
            "Concentration1":"No Major",
            "Type1":"Major",
            "Concentration2":"",
            "Type2":"",
            "CredHrs":"4",
            "SettledInd":"Y",
            "FullPart":"Part",
            "PhoneNbr":"",
            "RegDt":"11/30/2022"
        },
        {
            "StudentId":"U70270028",
            "StudentDashId":"U70-27-0028",
            "StudentFirst":"Skipper",
            "StudentMiddle":"",
            "StudentLast":"Bonaire",
            "StudentName":"Bonaire,Skipper",
            "Email":"BonaireS@bu.edu",
            "RegStatus":"REG",
            "ClassYr":"Grad 3rd",
            "Col":"MET",
            "Pgm":"49",
            "Concentration1":"Software Development",
            "Type1":"Major",
            "Concentration2":"",
            "Type2":"",
            "CredHrs":"4",
            "SettledInd":"Y",
            "FullPart":"Part",
            "PhoneNbr":"",
            "RegDt":"01/03/2023"
        },
        {
            "StudentId":"U79451588",
            "StudentDashId":"U79-45-1588",
            "StudentFirst":"Alika",
            "StudentMiddle":"",
            "StudentLast":"Bottrill",
            "StudentName":"Bottrill,Alika",
            "Email":"BottrillA@bu.edu",
            "RegStatus":"REG",
            "ClassYr":"Nondeg",
            "Col":"MET",
            "Pgm":"40",
            "Concentration1":"No Major",
            "Type1":"Major",
            "Concentration2":"",
            "Type2":"",
            "CredHrs":"4",
            "SettledInd":"Y",
            "FullPart":"Part",
            "PhoneNbr":"",
            "RegDt":"11/16/2022"
        },
        {
            "StudentId":"U71518753",
            "StudentDashId":"U71-51-8753",
            "StudentFirst":"Osbourne",
            "StudentMiddle":"",
            "StudentLast":"Castel",
            "StudentName":"Castel,Osbourne",
            "Email":"CastelO@bu.edu",
            "RegStatus":"REG",
            "ClassYr":"Nondeg",
            "Col":"MET",
            "Pgm":"40",
            "Concentration1":"No Major",
            "Type1":"Major",
            "Concentration2":"",
            "Type2":"",
            "CredHrs":"4",
            "SettledInd":"Y",
            "FullPart":"Part",
            "PhoneNbr":"",
            "RegDt":"11/15/2022"
        },
        {
            "StudentId":"U82312547",
            "StudentDashId":"U82-31-2547",
            "StudentFirst":"Veronika",
            "StudentMiddle":"",
            "StudentLast":"Cesco",
            "StudentName":"Cesco,Veronika",
            "Email":"CescoV@bu.edu",
            "RegStatus":"REG",
            "ClassYr":"Grad 4th",
            "Col":"MET",
            "Pgm":"49",
            "Concentration1":"Computer Info Systms",
            "Type1":"Major",
            "Concentration2":"IT project Managemnt",
            "Type2":"Subcn",
            "CredHrs":"4",
            "SettledInd":"Y",
            "FullPart":"Part",
            "PhoneNbr":"",
            "RegDt":"01/04/2023"
        },
        {
            "StudentId":"U10332425",
            "StudentDashId":"U10-33-2425",
            "StudentFirst":"Nalani",
            "StudentMiddle":"",
            "StudentLast":"Claris",
            "StudentName":"Claris,Nalani",
            "Email":"ClarisN@bu.edu",
            "RegStatus":"REG",
            "ClassYr":"Grad 2nd",
            "Col":"MET",
            "Pgm":"49",
            "Concentration1":"Computer Info Systms",
            "Type1":"Major",
            "Concentration2":"IT project Managemnt",
            "Type2":"Subcn",
            "CredHrs":"4",
            "SettledInd":"Y",
            "FullPart":"Part",
            "PhoneNbr":"",
            "RegDt":"12/06/2022"
        },
        {
            "StudentId":"U25761203",
            "StudentDashId":"U25-76-1203",
            "StudentFirst":"Urbanus",
            "StudentMiddle":"",
            "StudentLast":"Clitheroe",
            "StudentName":"Clitheroe,Urbanus",
            "Email":"ClitheroeU@bu.edu",
            "RegStatus":"REG",
            "ClassYr":"Grad 1st",
            "Col":"MET",
            "Pgm":"42",
            "Concentration1":"Health Informatics",
            "Type1":"Major",
            "Concentration2":"",
            "Type2":"",
            "CredHrs":"4",
            "SettledInd":"N",
            "FullPart":"Full",
            "PhoneNbr":"",
            "RegDt":"01/09/2023"
        },
        {
            "StudentId":"U65443909",
            "StudentDashId":"U65-44-3909",
            "StudentFirst":"Ali",
            "StudentMiddle":"",
            "StudentLast":"Coneron",
            "StudentName":"Coneron,Ali",
            "Email":"ConeronA@bu.edu",
            "RegStatus":"REG",
            "ClassYr":"Nondeg",
            "Col":"MET",
            "Pgm":"40",
            "Concentration1":"No Major",
            "Type1":"Major",
            "Concentration2":"",
            "Type2":"",
            "CredHrs":"4",
            "SettledInd":"Y",
            "FullPart":"Part",
            "PhoneNbr":"",
            "RegDt":"11/15/2022"
        },
        {
            "StudentId":"U43203870",
            "StudentDashId":"U43-20-3870",
            "StudentFirst":"Ivory",
            "StudentMiddle":"Tan",
            "StudentLast":"Corzon",
            "StudentName":"Corzon,Ivory,Tan",
            "Email":"CorzonI@bu.edu",
            "RegStatus":"REG",
            "ClassYr":"Grad 2nd",
            "Col":"MET",
            "Pgm":"42",
            "Concentration1":"Computer Science",
            "Type1":"Major",
            "Concentration2":"",
            "Type2":"",
            "CredHrs":"4",
            "SettledInd":"Y",
            "FullPart":"Part",
            "PhoneNbr":"",
            "RegDt":"01/04/2023"
        },
        {
            "StudentId":"U51749303",
            "StudentDashId":"U51-74-9303",
            "StudentFirst":"Lawton",
            "StudentMiddle":"",
            "StudentLast":"Cowperthwaite",
            "StudentName":"Cowperthwaite,Lawton",
            "Email":"CowperthwaiteL@bu.edu",
            "RegStatus":"REG",
            "ClassYr":"Nondeg",
            "Col":"MET",
            "Pgm":"40",
            "Concentration1":"No Major",
            "Type1":"Major",
            "Concentration2":"",
            "Type2":"",
            "CredHrs":"4",
            "SettledInd":"Y",
            "FullPart":"Part",
            "PhoneNbr":"",
            "RegDt":"12/19/2022"
        },
        {"StudentId":"U34565776",
            "StudentDashId":"U34-56-5776",
            "StudentFirst":"Tracee",
            "StudentMiddle":"",
            "StudentLast":"Cowton",
            "StudentName":"Cowton,Tracee",
            "Email":"CowtonT@bu.edu",
            "RegStatus":"REG",
            "ClassYr":"Grad 1st",
            "Col":"MET",
            "Pgm":"42",
            "Concentration1":"Computer Science",
            "Type1":"Major",
            "Concentration2":"",
            "Type2":"",
            "CredHrs":"4",
            "SettledInd":"Y",
            "FullPart":"Full",
            "PhoneNbr":"",
            "RegDt":"01/20/2023"
        },
        {
            "StudentId":"U32989195",
            "StudentDashId":"U32-98-9195",
            "StudentFirst":"Deck",
            "StudentMiddle":"",
            "StudentLast":"Craine",
            "StudentName":"Craine,Deck",
            "Email":"CraineD@bu.edu",
            "RegStatus":"REG",
            "ClassYr":"Grad 3rd",
            "Col":"MET",
            "Pgm":"49",
            "Concentration1":"Computer Info Systms",
            "Type1":"Major",
            "Concentration2":"IT project Managemnt",
            "Type2":"Subcn",
            "CredHrs":"4",
            "SettledInd":"Y",
            "FullPart":"Part",
            "PhoneNbr":"",
            "RegDt":"11/23/2022"
        },
        {
            "StudentId":"U87570131",
            "StudentDashId":"U87-57-0131",
            "StudentFirst":"Renaldo",
            "StudentMiddle":"Lee",
            "StudentLast":"Dotson",
            "StudentName":"Dotson,Renaldo,Lee",
            "Email":"DotsonR@bu.edu",
            "RegStatus":"REG",
            "ClassYr":"Grad 2nd",
            "Col":"MET",
            "Pgm":"49",
            "Concentration1":"Software Development",
            "Type1":"Major",
            "Concentration2":"",
            "Type2":"",
            "CredHrs":"4",
            "SettledInd":"Y",
            "FullPart":"Part",
            "PhoneNbr":"",
            "RegDt":"10/24/2022"
        },
        {
            "StudentId":"U87207965",
            "StudentDashId":"U87-20-7965",
            "StudentFirst":"Morissa",
            "StudentMiddle":"Bailey",
            "StudentLast":"Drackford",
            "StudentName":"Drackford,Morissa,Bailey",
            "Email":"DrackfordM@bu.edu",
            "RegStatus":"REG",
            "ClassYr":"Grad 3rd",
            "Col":"MET",
            "Pgm":"49",
            "Concentration1":"Computer Info Systms",
            "Type1":"Major",
            "Concentration2":"Data Analytics",
            "Type2":"Subcn",
            "CredHrs":"4",
            "SettledInd":"Y",
            "FullPart":"Part",
            "PhoneNbr":"",
            "RegDt":"12/30/2022"
        },
        {
            "StudentId":"U65376465",
            "StudentDashId":"U65-37-6465",
            "StudentFirst":"Margaretta",
            "StudentMiddle":"",
            "StudentLast":"Eddis",
            "StudentName":"Eddis,Margaretta",
            "Email":"EddisM@bu.edu",
            "RegStatus":"REG",
            "ClassYr":"Grad 2nd",
            "Col":"MET",
            "Pgm":"42",
            "Concentration1":"Computer Info Systms",
            "Type1":"Major",
            "Concentration2":"",
            "Type2":"",
            "CredHrs":"4",
            "SettledInd":"Y",
            "FullPart":"Part",
            "PhoneNbr":"",
            "RegDt":"01/10/2023"
        },
        {
            "StudentId":"U83007537",
            "StudentDashId":"U83-00-7537",
            "StudentFirst":"Kerry",
            "StudentMiddle":"",
            "StudentLast":"Fourman",
            "StudentName":"Fourman,Kerry",
            "Email":"FourmanK@bu.edu",
            "RegStatus":"REG",
            "ClassYr":"Grad 2nd",
            "Col":"MET",
            "Pgm":"49",
            "Concentration1":"Software Development",
            "Type1":"Major",
            "Concentration2":"",
            "Type2":"",
            "CredHrs":"4",
            "SettledInd":"Y",
            "FullPart":"Part",
            "PhoneNbr":"",
            "RegDt":"10/22/2022"
        },
        {
            "StudentId":"U71337766",
            "StudentDashId":"U71-33-7766",
            "StudentFirst":"Sawyere",
            "StudentMiddle":"",
            "StudentLast":"Harriman",
            "StudentName":"Harriman,Sawyere",
            "Email":"HarrimanS@bu.edu",
            "RegStatus":"REG",
            "ClassYr":"Grad 2nd",
            "Col":"MET",
            "Pgm":"49",
            "Concentration1":"Software Development",
            "Type1":"Major",
            "Concentration2":"",
            "Type2":"","CredHrs":"4",
            "SettledInd":"Y",
            "FullPart":"Part",
            "PhoneNbr":"",
            "RegDt":"11/21/2022"
        },
        {
            "StudentId":"U15250896",
            "StudentDashId":"U15-25-0896",
            "StudentFirst":"Gwenette",
            "StudentMiddle":"Linn",
            "StudentLast":"Hinz",
            "StudentName":"Hinz,Gwenette",
            "Email":"HinzG@bu.edu",
            "RegStatus":"REG",
            "ClassYr":"Grad 1st",
            "Col":"MET",
            "Pgm":"42",
            "Concentration1":"Software Development",
            "Type1":"Major",
            "Concentration2":"",
            "Type2":"",
            "CredHrs":"4",
            "SettledInd":"Y",
            "FullPart":"Full",
            "PhoneNbr":"",
            "RegDt":"12/30/2022"
        },
        {
            "StudentId":"U49370894",
            "StudentDashId":"U49-37-0894",
            "StudentFirst":"Ulberto",
            "StudentMiddle":"",
            "StudentLast":"Jager",
            "StudentName":"Jager,Ulberto",
            "Email":"JagerU@bu.edu",
            "RegStatus":"REG",
            "ClassYr":"Grad 3rd",
            "Col":"MET",
            "Pgm":"42",
            "Concentration1":"Computer Info Systms",
            "Type1":"Major",
            "Concentration2":"Databse Mgmt&Bus Int",
            "Type2":"Subcn",
            "CredHrs":"4",
            "SettledInd":"N",
            "FullPart":"Part",
            "PhoneNbr":"",
            "RegDt":"10/22/2022"
        },
        {
            "StudentId":"U49924857",
            "StudentDashId":"U49-92-4857",
            "StudentFirst":"Isacco",
            "StudentMiddle":"",
            "StudentLast":"Jahnisch",
            "StudentName":"Jahnisch,Isacco",
            "Email":"JahnischI@bu.edu",
            "RegStatus":"REG",
            "ClassYr":"Grad 2nd",
            "Col":"MET",
            "Pgm":"49",
            "Concentration1":"Software Development",
            "Type1":"Major",
            "Concentration2":"",
            "Type2":"",
            "CredHrs":"4",
            "SettledInd":"N",
            "FullPart":"Part",
            "PhoneNbr":"",
            "RegDt":"01/10/2023"
        },
        {
            "StudentId":"U16412496",
            "StudentDashId":"U16-41-2496",
            "StudentFirst":"Niki",
            "StudentMiddle":"",
            "StudentLast":"Klee",
            "StudentName":"Klee,Niki",
            "Email":"KleeN@bu.edu",
            "RegStatus":"REG",
            "ClassYr":"Grad 2nd",
            "Col":"MET",
            "Pgm":"49",
            "Concentration1":"Software Development",
            "Type1":"Major",
            "Concentration2":"",
            "Type2":"",
            "CredHrs":"4",
            "SettledInd":"Y",
            "FullPart":"Part",
            "PhoneNbr":"",
            "RegDt":"10/22/2022"
        },
        {
            "StudentId":"U12613250",
            "StudentDashId":"U12-61-3250",
            "StudentFirst":"Lynnett",
            "StudentMiddle":"",
            "StudentLast":"Lawee",
            "StudentName":"Lawee,Lynnett",
            "Email":"LaweeL@bu.edu",
            "RegStatus":"REG",
            "ClassYr":"Nondeg",
            "Col":"MET",
            "Pgm":"40",
            "Concentration1":"No Major",
            "Type1":"Major",
            "Concentration2":"",
            "Type2":"",
            "CredHrs":"4",
            "SettledInd":"Y",
            "FullPart":"Part",
            "PhoneNbr":"",
            "RegDt":"12/01/2022"
        },
        {
            "StudentId":"U29793288",
            "StudentDashId":"U29-79-3288",
            "StudentFirst":"Nora",
            "StudentMiddle":"",
            "StudentLast":"Loble",
            "StudentName":"Loble,Nora",
            "Email":"LobleN@bu.edu",
            "RegStatus":"REG",
            "ClassYr":"Grad 3rd",
            "Col":"MET",
            "Pgm":"49",
            "Concentration1":"Software Development",
            "Type1":"Major",
            "Concentration2":"",
            "Type2":"",
            "CredHrs":"4",
            "SettledInd":"Y",
            "FullPart":"Part",
            "PhoneNbr":"",
            "RegDt":"10/22/2022"
        },
        {
            "StudentId":"U19811639",
            "StudentDashId":"U19-81-1639",
            "StudentFirst":"Danya",
            "StudentMiddle":"",
            "StudentLast":"Lovelady",
            "StudentName":"Lovelady,Danya",
            "Email":"LoveladyD@bu.edu",
            "RegStatus":"REG",
            "ClassYr":"Grad 3rd",
            "Col":"MET",
            "Pgm":"42",
            "Concentration1":"Computer Info Systms",
            "Type1":"Major",
            "Concentration2":"Computer Networks",
            "Type2":"Subcn",
            "CredHrs":"4",
            "SettledInd":"Y",
            "FullPart":"Part",
            "PhoneNbr":"",
            "RegDt":"10/22/2022"
        },
        {
            "StudentId":"U11004078",
            "StudentDashId":"U11-00-4078",
            "StudentFirst":"Rudyard",
            "StudentMiddle":"",
            "StudentLast":"MacGovern",
            "StudentName":"MacGovern,Rudyard",
            "Email":"MacGovernR@bu.edu",
            "RegStatus":"REG",
            "ClassYr":"Grad 2nd",
            "Col":"MET",
            "Pgm":"49",
            "Concentration1":"Software Development",
            "Type1":"Major",
            "Concentration2":"",
            "Type2":"",
            "CredHrs":"4",
            "SettledInd":"Y",
            "FullPart":"Part",
            "PhoneNbr":"",
            "RegDt":"10/22/2022"
        },
        {
            "StudentId":"U86911162",
            "StudentDashId":"U86-91-1162",
            "StudentFirst":"Kingston",
            "StudentMiddle":"Sara",
            "StudentLast":"Margerrison",
            "StudentName":"Margerrison,Kingston,Sara",
            "Email":"MargerrisonK@bu.edu",
            "RegStatus":"REG",
            "ClassYr":"Grad 3rd",
            "Col":"MET",
            "Pgm":"49",
            "Concentration1":"Computer Info Systms",
            "Type1":"Major",
            "Concentration2":"IT project Managemnt",
            "Type2":"Subcn",
            "CredHrs":"4",
            "SettledInd":"N",
            "FullPart":"Part",
            "PhoneNbr":"",
            "RegDt":"10/22/2022"
        },
        {
            "StudentId":"U77347864",
            "StudentDashId":"U77-34-7864",
            "StudentFirst":"Loleta",
            "StudentMiddle":"",
            "StudentLast":"Millott",
            "StudentName":"Millott,Loleta",
            "Email":"MillottL@bu.edu",
            "RegStatus":"REG",
            "ClassYr":"Grad 2nd",
            "Col":"MET",
            "Pgm":"49",
            "Concentration1":"Software Development",
            "Type1":"Major",
            "Concentration2":"",
            "Type2":"",
            "CredHrs":"4",
            "SettledInd":"Y",
            "FullPart":"Part",
            "PhoneNbr":"",
            "RegDt":"10/22/2022"
        },
        {
            "StudentId":"U37800149",
            "StudentDashId":"U37-80-0149",
            "StudentFirst":"Kain",
            "StudentMiddle":"",
            "StudentLast":"Oki",
            "StudentName":"Oki,Kain",
            "Email":"OkiK@bu.edu",
            "RegStatus":"REG",
            "ClassYr":"Nondeg",
            "Col":"MET",
            "Pgm":"0",
            "Concentration1":"No Major",
            "Type1":"Major",
            "Concentration2":"",
            "Type2":"","CredHrs":"4",
            "SettledInd":"N",
            "FullPart":"Part",
            "PhoneNbr":"",
            "RegDt":"01/17/2023"
        },
        {
            "StudentId":"U59540600",
            "StudentDashId":"U59-54-0600",
            "StudentFirst":"Hersh",
            "StudentMiddle":"",
            "StudentLast":"Paolino",
            "StudentName":"Paolino,Hersh",
            "Email":"PaolinoH@bu.edu",
            "RegStatus":"REG",
            "ClassYr":"Grad 2nd",
            "Col":"MET",
            "Pgm":"49",
            "Concentration1":"Computer Info Systms",
            "Type1":"Major",
            "Concentration2":"IT project Managemnt",
            "Type2":"Subcn",
            "CredHrs":"4",
            "SettledInd":"Y",
            "FullPart":"Part",
            "PhoneNbr":"",
            "RegDt":"10/23/2022"
        },
        {
            "StudentId":"U94932673",
            "StudentDashId":"U94-93-2673",
            "StudentFirst":"Wernher",
            "StudentMiddle":"",
            "StudentLast":"Peirce",
            "StudentName":"Peirce,Wernher",
            "Email":"PeirceW@bu.edu",
            "RegStatus":"REG",
            "ClassYr":"Grad 1st",
            "Col":"MET",
            "Pgm":"42",
            "Concentration1":"Computer Science",
            "Type1":"Major",
            "Concentration2":"",
            "Type2":"",
            "CredHrs":"4",
            "SettledInd":"Y",
            "FullPart":"Full",
            "PhoneNbr":"",
            "RegDt":"01/20/2023"
        },
        {
            "StudentId":"U14810016",
            "StudentDashId":"U14-81-0016",
            "StudentFirst":"Lou",
            "StudentMiddle":"",
            "StudentLast":"Perfili",
            "StudentName":"Perfili,Lou",
            "Email":"PerfiliL@bu.edu",
            "RegStatus":"REG",
            "ClassYr":"Nondeg",
            "Col":"MET",
            "Pgm":"40",
            "Concentration1":"No Major",
            "Type1":"Major",
            "Concentration2":"",
            "Type2":"",
            "CredHrs":"4",
            "SettledInd":"Y",
            "FullPart":"Part",
            "PhoneNbr":"",
            "RegDt":"11/28/2022"
        },
        {
            "StudentId":"U25140621",
            "StudentDashId":"U25-14-0621",
            "StudentFirst":"Belicia",
            "StudentMiddle":"",
            "StudentLast":"Philbin",
            "StudentName":"Philbin,Belicia",
            "Email":"PhilbinB@bu.edu",
            "RegStatus":"REG",
            "ClassYr":"Grad 1st",
            "Col":"MET","Pgm":"49",
            "Concentration1":"Software Development",
            "Type1":"Major",
            "Concentration2":"",
            "Type2":"",
            "CredHrs":"4",
            "SettledInd":"Y",
            "FullPart":"Part",
            "PhoneNbr":"",
            "RegDt":"11/28/2022"
        },
        {
            "StudentId":"U64438875",
            "StudentDashId":"U64-43-8875",
            "StudentFirst":"Louisa",
            "StudentMiddle":"",
            "StudentLast":"Retter",
            "StudentName":"Retter,Louisa",
            "Email":"RetterL@bu.edu",
            "RegStatus":"REG",
            "ClassYr":"Grad 4th",
            "Col":"MET",
            "Pgm":"49",
            "Concentration1":"Software Development",
            "Type1":"Major",
            "Concentration2":"",
            "Type2":"",
            "CredHrs":"4",
            "SettledInd":"Y",
            "FullPart":"Part",
            "PhoneNbr":"",
            "RegDt":"01/10/2023"
        },
        {
            "StudentId":"U31976781",
            "StudentDashId":"U31-97-6781",
            "StudentFirst":"Joela","StudentMiddle":"",
            "StudentLast":"Riepl",
            "StudentName":"Riepl,Joela,",
            "Email":"RieplJ@bu.edu",
            "RegStatus":"REG",
            "ClassYr":"Grad 1st",
            "Col":"MET",
            "Pgm":"49",
            "Concentration1":"Software Development",
            "Type1":"Major",
            "Concentration2":"",
            "Type2":"","CredHrs":"4",
            "SettledInd":"Y",
            "FullPart":"Part",
            "PhoneNbr":"",
            "RegDt":"10/22/2022"
        },
        {
            "StudentId":"U28076747",
            "StudentDashId":"U28-07-6747",
            "StudentFirst":"Sabina",
            "StudentMiddle":"",
            "StudentLast":"Sackey",
            "StudentName":"Sackey,Sabina",
            "Email":"SackeyS@bu.edu",
            "RegStatus":"REG",
            "ClassYr":"Grad 4th",
            "Col":"MET",
            "Pgm":"49",
            "Concentration1":"Computer Info Systms",
            "Type1":"Major",
            "Concentration2":"",
            "Type2":"",
            "CredHrs":"4",
            "SettledInd":"Y",
            "FullPart":"Part",
            "PhoneNbr":"",
            "RegDt":"10/22/2022"
        },
        {
            "StudentId":"U61324140",
            "StudentDashId":"U61-32-4140",
            "StudentFirst":"Kira",
            "StudentMiddle":"",
            "StudentLast":"Silbersak",
            "StudentName":"Silbersak,Kira",
            "Email":"SilbersakK@bu.edu",
            "RegStatus":"REG",
            "ClassYr":"Grad 4th",
            "Col":"MET",
            "Pgm":"49",
            "Concentration1":"Computer Info Systms",
            "Type1":"Major",
            "Concentration2":"",
            "Type2":"",
            "CredHrs":"4",
            "SettledInd":"Y",
            "FullPart":"Part",
            "PhoneNbr":"",
            "RegDt":"10/27/2022"
        },
        {
            "StudentId":"U99979695",
            "StudentDashId":"U99-97-9695",
            "StudentFirst":"Russ",
            "StudentMiddle":"",
            "StudentLast":"Sille",
            "StudentName":"Sille,Russ",
            "Email":"SilleR@bu.edu",
            "RegStatus":"REG",
            "ClassYr":"Grad 3rd",
            "Col":"MET",
            "Pgm":"49",
            "Concentration1":"Computer Info Systms",
            "Type1":"Major",
            "Concentration2":"IT project Managemnt",
            "Type2":"Subcn",
            "CredHrs":"4",
            "SettledInd":"Y",
            "FullPart":"Part",
            "PhoneNbr":"",
            "RegDt":"10/22/2022"
        },
        {
            "StudentId":"U82868644",
            "StudentDashId":"U82-86-8644",
            "StudentFirst":"Rose",
            "StudentMiddle":"",
            "StudentLast":"Snarr",
            "StudentName":"Snarr,Rose",
            "Email":"SnarrR@bu.edu",
            "RegStatus":"REG",
            "ClassYr":"Grad 3rd",
            "Col":"MET",
            "Pgm":"49",
            "Concentration1":"Computer Info Systms",
            "Type1":"Major",
            "Concentration2":"IT project Managemnt",
            "Type2":"Subcn",
            "CredHrs":"4",
            "SettledInd":"Y",
            "FullPart":"Part",
            "PhoneNbr":"",
            "RegDt":"12/22/2022"
        },
        {
            "StudentId":"U13466334",
            "StudentDashId":"U13-46-6334",
            "StudentFirst":"Xi",
            "StudentMiddle":"",
            "StudentLast":"Son",
            "StudentName":"Son,Xi",
            "Email":"SonX@bu.edu",
            "RegStatus":"REG",
            "ClassYr":"Grad 2nd",
            "Col":"MET",
            "Pgm":"49",
            "Concentration1":"Computer Info Systms",
            "Type1":"Major",
            "Concentration2":"IT project Managemnt",
            "Type2":"Subcn",
            "CredHrs":"4",
            "SettledInd":"Y",
            "FullPart":"Part",
            "PhoneNbr":"",
            "RegDt":"12/06/2022"
        },
        {
            "StudentId":"U24672585",
            "StudentDashId":"U24-67-2585",
            "StudentFirst":"Angelita",
            "StudentMiddle":"",
            "StudentLast":"Suggett",
            "StudentName":"Suggett,Angelita",
            "Email":"SuggettA@bu.edu",
            "RegStatus":"REG",
            "ClassYr":"Grad 3rd",
            "Col":"MET",
            "Pgm":"49",
            "Concentration1":"Software Development",
            "Type1":"Major",
            "Concentration2":"",
            "Type2":"",
            "CredHrs":"4",
            "SettledInd":"Y",
            "FullPart":"Part",
            "PhoneNbr":"",
            "RegDt":"11/09/2022"
        },
        {
            "StudentId":"U73686009",
            "StudentDashId":"U73-68-6009",
            "StudentFirst":"Carita",
            "StudentMiddle":"",
            "StudentLast":"Telfer",
            "StudentName":"Telfer,Carita",
            "Email":"TelferC@bu.edu",
            "RegStatus":"REG",
            "ClassYr":"Grad 4th",
            "Col":"MET",
            "Pgm":"42",
            "Concentration1":"Computer Science",
            "Type1":"Major",
            "Concentration2":"",
            "Type2":"",
            "CredHrs":"4",
            "SettledInd":"Y",
            "FullPart":"Part",
            "PhoneNbr":"",
            "RegDt":"01/03/2023"
        },
        {
            "StudentId":"U84860814",
            "StudentDashId":"U84-86-0814",
            "StudentFirst":"Fang",
            "StudentMiddle":"",
            "StudentLast":"Xiaotong",
            "StudentName":"Xiaotong,Fang",
            "Email":"XiaotongF@bu.edu",
            "RegStatus":"REG",
            "ClassYr":"Nondeg",
            "Col":"MET",
            "Pgm":"40",
            "Concentration1":"No Major",
            "Type1":"Major",
            "Concentration2":"",
            "Type2":"",
            "CredHrs":"4",
            "SettledInd":"Y",
            "FullPart":"Part",
            "PhoneNbr":"",
            "RegDt":"12/08/2022"
        }
    ]

    try {
        studentMock.map(async (student) => {
            const data = student; //JSON of object to insert
            console.log(student.studentname)
            await client.query(
                "INSERT INTO STUDENTS (StudentId, StudentDashId, StudentFirst, StudentMiddle, StudentLast, StudentName, Email, RegStatus, ClassYear, Col, Pgm, Concentration1, Type1, Concentration2, Type2, FullPart, PhoneNbr) " +
                "VALUES($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17);", [data.StudentId, data.StudentDashId, data.StudentFirst, data.StudentMiddle, data.StudentLast, data.StudentName, data.Email, data.RegStatus, data.ClassYear, data.Col, data.Pgm, data.Concentration1, data.Type1, data.Concentration2, data.Type2, data.FullPart, data.PhoneNbr]
            );
        })}
    catch (err) {
        console.log('ERROR')
        res.status(500).send("Server error")
    }
    finally {
        console.log('SEND')
        res.status(200).send("Roster complete")
    }
});
